# Generated by Django 5.1.2 on 2024-11-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_created=True)),
                ('count', models.IntegerField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=500000)),
                ('time_update', models.DateTimeField(auto_now_add=True)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appFood.menu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appFood.orders')),
            ],
        ),
    ]
