# Generated by Django 5.1.2 on 2024-11-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0004_alter_orders_address_alter_orders_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
