# Generated by Django 5.1.2 on 2024-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0006_alter_orderin_menu_id_alter_orderin_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderin',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderin',
            name='menu_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderin',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderin',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=500000, null=True),
        ),
        migrations.AlterField(
            model_name='orderin',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderin',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
